-- Creacion de la base de datos con datos
-- Se crea la institucion
INSERT INTO INSTITUCIONES (NOMBRE)
VALUES ('CodigoCreativo');
-- Se crean los perfiles
INSERT INTO PERFILES (NOMBRE_PERFIL, ESTADO)
VALUES ('Administrador', 'ACTIVO');
INSERT INTO PERFILES (NOMBRE_PERFIL, ESTADO)
VALUES ('Auxiliar administrativo', 'ACTIVO');
INSERT INTO PERFILES (NOMBRE_PERFIL, ESTADO)
VALUES ('Ingeniero biomédico', 'ACTIVO');
INSERT INTO PERFILES (NOMBRE_PERFIL, ESTADO)
VALUES ('Tecnico', 'ACTIVO');
-- Se crean los usuarios
INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDO, ID_PERFIL, ID_INSTITUCION, EMAIL, NOMBRE_USUARIO, CONTRASENIA, ESTADO, FECHA_NACIMIENTO)
VALUES ('11111111', 'Admin', 'Admin', (SELECT ID_PERFIL FROM PERFILES WHERE NOMBRE_PERFIL LIKE 'Administrador'), (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE INSTITUCIONES.NOMBRE LIKE 'CodigoCreativo'), 'admin@admin.com', 'admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'ACTIVO', DATE '2000-11-01');
INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDO, ID_PERFIL, ID_INSTITUCION, EMAIL, NOMBRE_USUARIO, CONTRASENIA, ESTADO, FECHA_NACIMIENTO)
VALUES ('22222222', 'Marcelo', 'Puentes', (SELECT ID_PERFIL FROM PERFILES WHERE NOMBRE_PERFIL LIKE 'Auxiliar administrativo'), (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE INSTITUCIONES.NOMBRE LIKE 'CodigoCreativo'), 'marcelop@admin.com', 'marcelo.puentes', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'ACTIVO', DATE '2000-01-01');
INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDO, ID_PERFIL, ID_INSTITUCION, EMAIL, NOMBRE_USUARIO, CONTRASENIA, ESTADO, FECHA_NACIMIENTO)
VALUES ('33333333', 'Madgalena', 'Rivas', (SELECT ID_PERFIL FROM PERFILES WHERE NOMBRE_PERFIL LIKE 'Ingeniero biomédico'), (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE INSTITUCIONES.NOMBRE LIKE 'CodigoCreativo'), 'madgalena@admin.com', 'madgalena.rivas', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'ACTIVO', DATE '2000-02-02');
INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDO, ID_PERFIL, ID_INSTITUCION, EMAIL, NOMBRE_USUARIO, CONTRASENIA, ESTADO, FECHA_NACIMIENTO)
VALUES ('44444444', 'Esteban', 'Paredes', (SELECT ID_PERFIL FROM PERFILES WHERE NOMBRE_PERFIL LIKE 'Tecnico'), (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE INSTITUCIONES.NOMBRE LIKE 'CodigoCreativo'), 'esteban@admin.com', 'esteban.paredes', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'ACTIVO', DATE '2000-03-03');
INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDO, ID_PERFIL, ID_INSTITUCION, EMAIL, NOMBRE_USUARIO, CONTRASENIA, ESTADO, FECHA_NACIMIENTO)
VALUES ('55555555', 'Pedro', 'Artemis', (SELECT ID_PERFIL FROM PERFILES WHERE NOMBRE_PERFIL LIKE 'Administrador'), (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE INSTITUCIONES.NOMBRE LIKE 'CodigoCreativo'), 'pedro@admin.com', 'pedro.artemis', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'ACTIVO', DATE '2000-04-04');
INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDO, ID_PERFIL, ID_INSTITUCION, EMAIL, NOMBRE_USUARIO, CONTRASENIA, ESTADO, FECHA_NACIMIENTO)
VALUES ('66666666', 'Ramon', 'Mitre', (SELECT ID_PERFIL FROM PERFILES WHERE NOMBRE_PERFIL LIKE 'Auxiliar administrativo'), (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE INSTITUCIONES.NOMBRE LIKE 'CodigoCreativo'), 'ramon@admin.com', 'ramon.mitre', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'ACTIVO', DATE '2000-05-05');
INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDO, ID_PERFIL, ID_INSTITUCION, EMAIL, NOMBRE_USUARIO, CONTRASENIA, ESTADO, FECHA_NACIMIENTO)
VALUES ('77777777', 'Alvaro', 'Salazar', (SELECT ID_PERFIL FROM PERFILES WHERE NOMBRE_PERFIL LIKE 'Ingeniero biomédico'), (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE INSTITUCIONES.NOMBRE LIKE 'CodigoCreativo'), 'alvaro@admin.com', 'alvaro.salazar', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'ACTIVO', DATE '2000-06-06');
--Se crean telefonos de usuarios
INSERT INTO USUARIOS_TELEFONOS (ID_USUARIO, NUMERO) VALUES ((SELECT ID_USUARIO FROM USUARIOS WHERE NOMBRE_USUARIO LIKE 'admin'), '095478654');
INSERT INTO USUARIOS_TELEFONOS (ID_USUARIO, NUMERO) VALUES ((SELECT ID_USUARIO FROM USUARIOS WHERE NOMBRE_USUARIO LIKE 'marcelo.puentes'), '098224558');
INSERT INTO USUARIOS_TELEFONOS (ID_USUARIO, NUMERO) VALUES ((SELECT ID_USUARIO FROM USUARIOS WHERE NOMBRE_USUARIO LIKE 'alvaro.salazar'), '099984521');
-- Se crean los tipos de equipos
INSERT INTO TIPOS_EQUIPOS (NOMBRE_TIPO) VALUES ('Desfribilador');
INSERT INTO TIPOS_EQUIPOS (NOMBRE_TIPO) VALUES ('Monitor de signos');
INSERT INTO TIPOS_EQUIPOS (NOMBRE_TIPO) VALUES ('Electroquirurjico');
INSERT INTO TIPOS_EQUIPOS (NOMBRE_TIPO) VALUES ('Anestesiometro');
INSERT INTO TIPOS_EQUIPOS (NOMBRE_TIPO) VALUES ('Rayos x');
INSERT INTO TIPOS_EQUIPOS (NOMBRE_TIPO) VALUES ('Nebulizador');
INSERT INTO TIPOS_EQUIPOS (NOMBRE_TIPO) VALUES ('Electrocardiógrafo');
-- Se crean las Marcas de equipos
INSERT INTO MARCAS_MODELO (NOMBRE) VALUES ('Welch Allyn');
INSERT INTO MARCAS_MODELO (NOMBRE) VALUES ('Health o Meter');
INSERT INTO MARCAS_MODELO (NOMBRE) VALUES ('Draguer');
INSERT INTO MARCAS_MODELO (NOMBRE) VALUES ('Thomas');
INSERT INTO MARCAS_MODELO (NOMBRE) VALUES ('Omron');
INSERT INTO MARCAS_MODELO (NOMBRE) VALUES ('EDAN');
INSERT INTO MARCAS_MODELO (NOMBRE) VALUES ('Mindray');
-- Se crean los modelos de equipos
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE)
VALUES ((SELECT ID_MARCA FROM MARCAS_MODELO WHERE NOMBRE LIKE 'Welch Allyn'), 'Kaspery');
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE)
VALUES ((SELECT ID_MARCA FROM MARCAS_MODELO WHERE NOMBRE LIKE 'Health o Meter'), 'Rowback');
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE)
VALUES ((SELECT ID_MARCA FROM MARCAS_MODELO WHERE NOMBRE LIKE 'Draguer'), '700G');
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE)
VALUES ((SELECT ID_MARCA FROM MARCAS_MODELO WHERE NOMBRE LIKE 'Thomas'), '007');
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE)
VALUES ((SELECT ID_MARCA FROM MARCAS_MODELO WHERE NOMBRE LIKE 'Omron'), 'NE-C801');
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE)
VALUES ((SELECT ID_MARCA FROM MARCAS_MODELO WHERE NOMBRE LIKE 'EDAN'), 'M50');
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE)
VALUES ((SELECT ID_MARCA FROM MARCAS_MODELO WHERE NOMBRE LIKE 'EDAN'), 'SE 301');
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE)
VALUES ((SELECT ID_MARCA FROM MARCAS_MODELO WHERE NOMBRE LIKE 'Mindray'), 'BeneHeart D3');
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE)
VALUES ((SELECT ID_MARCA FROM MARCAS_MODELO WHERE NOMBRE LIKE 'Mindray'), 'Wato EX 65');
-- Se crean los países
INSERT INTO PAISES (NOMBRE) VALUES ('Uruguay');
INSERT INTO PAISES (NOMBRE) VALUES ('Argentina');
INSERT INTO PAISES (NOMBRE) VALUES ('Brasil');
INSERT INTO PAISES (NOMBRE) VALUES ('Chile');
-- Se crean permisos
INSERT INTO PERMISOS (TIPO_PERMISO) VALUES ('Agregar');
INSERT INTO PERMISOS (TIPO_PERMISO) VALUES ('Borrar');
INSERT INTO PERMISOS (TIPO_PERMISO) VALUES ('Editar');
INSERT INTO PERMISOS (TIPO_PERMISO) VALUES ('Ver');
-- Se crean proveedores
INSERT INTO PROVEEDORES_EQUIPOS (NOMBRE) VALUES ('MedicTube');
INSERT INTO PROVEEDORES_EQUIPOS (NOMBRE) VALUES ('MoniVita');
INSERT INTO PROVEEDORES_EQUIPOS (NOMBRE) VALUES ('Desfribilados');
INSERT INTO PROVEEDORES_EQUIPOS (NOMBRE) VALUES ('Anestesic');
-- Se crean tipos de intervenciones
INSERT INTO TIPOS_INTERVENCIONES (NOMBRE_TIPO, ESTADO) VALUES ('Predictivo', 'ACTIVO');
INSERT INTO TIPOS_INTERVENCIONES (NOMBRE_TIPO, ESTADO) VALUES ('Correctivo', 'ACTIVO');
INSERT INTO TIPOS_INTERVENCIONES (NOMBRE_TIPO, ESTADO) VALUES ('Preventivo', 'ACTIVO');
-- Se crean ubicaciones
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('Odontologia', 'Policlínico', 1, 2, null, (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE NOMBRE LIKE 'CodigoCreativo'), 'INACTIVO');
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('Obstreta', 'Policlínico', 2, 2, null, (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE NOMBRE LIKE 'CodigoCreativo'), 'ACTIVO');
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('Box Rapido', 'Emergencia', 1, 1, null, (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE NOMBRE LIKE 'CodigoCreativo'), 'ACTIVO');
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('Cirugia', 'CTI', 1, 2, null, (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE NOMBRE LIKE 'CodigoCreativo'), 'ACTIVO');
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('Limpieza', 'Emergencia', 1, 1, null, (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE NOMBRE LIKE 'CodigoCreativo'), 'ACTIVO');
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('Sala de espera', 'Emergencia', 1, 1, 1, (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE NOMBRE LIKE 'CodigoCreativo'), 'ACTIVO');
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('Cuidados intermedios', 'Internación', 3, 3, 2, (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE NOMBRE LIKE 'CodigoCreativo'), 'INACTIVO');
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('Cuarentena', 'Internación', 1, 2, null, (SELECT ID_INSTITUCION FROM INSTITUCIONES WHERE NOMBRE LIKE 'CodigoCreativo'), 'ACTIVO');
-- Se crean las baja de ubicaciones
INSERT INTO PROYECTO.BAJA_UBICACIONES (ID_USUARIO, ID_UBICACION, RAZON, COMENTARIO, FECHA) VALUES ((SELECT ID_USUARIO FROM USUARIOS WHERE NOMBRE_USUARIO LIKE 'admin'), (SELECT ID_UBICACION FROM UBICACIONES WHERE NOMBRE LIKE 'Odontologia'), 'Cerrado por remodelacion', 'Cambio de piso', DATE '2023-11-27');
INSERT INTO PROYECTO.BAJA_UBICACIONES (ID_USUARIO, ID_UBICACION, RAZON, COMENTARIO, FECHA) VALUES ((SELECT ID_USUARIO FROM USUARIOS WHERE NOMBRE_USUARIO LIKE 'admin'), (SELECT ID_UBICACION FROM UBICACIONES WHERE NOMBRE LIKE 'Cuidados intermedios'), 'Cambio de nombre', 'ninguno', DATE '2023-12-17');
-- Se crean Equipos
INSERT INTO PROYECTO.EQUIPOS (ID_INTERNO, ID_UBICACION, NRO_SERIE, NOMBRE, ID_TIPO, ESTADO, ID_PROVEEDOR, ID_PAIS, ID_MODELO, IMAGEN, FECHA_ADQUISICION)
VALUES ('1001', (SELECT ID_UBICACION FROM UBICACIONES WHERE NOMBRE LIKE 'Box Rapido'), '123355533', 'Tensiometro', (SELECT ID_TIPO FROM TIPOS_EQUIPOS WHERE NOMBRE_TIPO LIKE 'Monitor de signos'), 'ACTIVO', (SELECT ID_PROVEEDOR FROM PROVEEDORES_EQUIPOS WHERE NOMBRE LIKE 'MoniVita'), (SELECT ID_PAIS FROM PAISES WHERE NOMBRE LIKE 'Uruguay'), (SELECT ID_MODELO FROM MODELOS_EQUIPOS WHERE NOMBRE LIKE 'Rowback'), 'https://i.ibb.co/X26FksG/tensiometro.jpg', DATE '2023-11-01');
INSERT INTO PROYECTO.EQUIPOS (ID_INTERNO, ID_UBICACION, NRO_SERIE, NOMBRE, ID_TIPO, ESTADO, ID_PROVEEDOR, ID_PAIS, ID_MODELO, IMAGEN, FECHA_ADQUISICION)
VALUES ('1002', (SELECT ID_UBICACION FROM UBICACIONES WHERE NOMBRE LIKE 'Cirugia'), '12255577', 'Anestesiometro cirugia', (SELECT ID_TIPO FROM TIPOS_EQUIPOS WHERE NOMBRE_TIPO LIKE 'Anestesiometro'), 'ACTIVO', (SELECT ID_PROVEEDOR FROM PROVEEDORES_EQUIPOS WHERE NOMBRE LIKE 'Anestesic'), (SELECT ID_PAIS FROM PAISES WHERE NOMBRE LIKE 'Uruguay'), (SELECT ID_MODELO FROM MODELOS_EQUIPOS WHERE NOMBRE LIKE '700G'), 'https://i.ibb.co/Ht5DfKp/mgoitd09.png', DATE '2020-11-11');
INSERT INTO PROYECTO.EQUIPOS (ID_INTERNO, ID_UBICACION, NRO_SERIE, NOMBRE, ID_TIPO, ESTADO, ID_PROVEEDOR, ID_PAIS, ID_MODELO, IMAGEN, FECHA_ADQUISICION)
VALUES ('1003', (SELECT ID_UBICACION FROM UBICACIONES WHERE NOMBRE LIKE 'Cuarentena'), '654456778', 'Nebulizador', (SELECT ID_TIPO FROM TIPOS_EQUIPOS WHERE NOMBRE_TIPO LIKE 'Nebulizador'), 'ACTIVO', (SELECT ID_PROVEEDOR FROM PROVEEDORES_EQUIPOS WHERE NOMBRE LIKE 'MedicTube'), (SELECT ID_PAIS FROM PAISES WHERE NOMBRE LIKE 'Uruguay'), (SELECT ID_MODELO FROM MODELOS_EQUIPOS WHERE NOMBRE LIKE 'NE-C801'), 'https://i.ibb.co/LRRHW2s/nebulizador-omron-NE-C801-1-977x1024-1.png', DATE '2020-11-08');
INSERT INTO PROYECTO.EQUIPOS (ID_INTERNO, ID_UBICACION, NRO_SERIE, NOMBRE, ID_TIPO, ESTADO, ID_PROVEEDOR, ID_PAIS, ID_MODELO, IMAGEN, FECHA_ADQUISICION)
VALUES ('1004', (SELECT ID_UBICACION FROM UBICACIONES WHERE NOMBRE LIKE 'Cirugia'), '544568786', 'Desfribilador CTI', (SELECT ID_TIPO FROM TIPOS_EQUIPOS WHERE NOMBRE_TIPO LIKE 'Desfribilador'), 'ACTIVO', (SELECT ID_PROVEEDOR FROM PROVEEDORES_EQUIPOS WHERE NOMBRE LIKE 'Desfribilados'), (SELECT ID_PAIS FROM PAISES WHERE NOMBRE LIKE 'Uruguay'), (SELECT ID_MODELO FROM MODELOS_EQUIPOS WHERE NOMBRE LIKE 'BeneHeart D3'), 'https://i.ibb.co/WVpb5s4/beneheath-d3-977x1024-1.png', DATE '2010-10-05');
INSERT INTO PROYECTO.EQUIPOS (ID_INTERNO, ID_UBICACION, NRO_SERIE, NOMBRE, ID_TIPO, ESTADO, ID_PROVEEDOR, ID_PAIS, ID_MODELO, IMAGEN, FECHA_ADQUISICION)
VALUES ('1005', (SELECT ID_UBICACION FROM UBICACIONES WHERE NOMBRE LIKE 'Cirugia'), '454644678', 'Cardiografo', (SELECT ID_TIPO FROM TIPOS_EQUIPOS WHERE NOMBRE_TIPO LIKE 'Electrocardiógrafo'), 'ACTIVO', (SELECT ID_PROVEEDOR FROM PROVEEDORES_EQUIPOS WHERE NOMBRE LIKE 'MedicTube'), (SELECT ID_PAIS FROM PAISES WHERE NOMBRE LIKE 'Uruguay'), (SELECT ID_MODELO FROM MODELOS_EQUIPOS WHERE NOMBRE LIKE 'SE 301'), 'https://i.ibb.co/qFhSVVb/edan-se-301-1-1.png', DATE '2017-03-10');
INSERT INTO PROYECTO.EQUIPOS (ID_INTERNO, ID_UBICACION, NRO_SERIE, NOMBRE, ID_TIPO, ESTADO, ID_PROVEEDOR, ID_PAIS, ID_MODELO, IMAGEN, FECHA_ADQUISICION)
VALUES ('1006', (SELECT ID_UBICACION FROM UBICACIONES WHERE NOMBRE LIKE 'Box Rapido'), '45875517', 'Anestesiometro emergencia', (SELECT ID_TIPO FROM TIPOS_EQUIPOS WHERE NOMBRE_TIPO LIKE 'Anestesiometro'), 'ACTIVO', (SELECT ID_PROVEEDOR FROM PROVEEDORES_EQUIPOS WHERE NOMBRE LIKE 'Anestesic'), (SELECT ID_PAIS FROM PAISES WHERE NOMBRE LIKE 'Uruguay'), (SELECT ID_MODELO FROM MODELOS_EQUIPOS WHERE NOMBRE LIKE 'Wato EX 65'), 'https://i.ibb.co/g6YL0F9/maquina-de-anestesia-mindray-wato-ex-65-1-977x1024-1.png', DATE '2019-05-20');
-- Se crean las intervenciones
INSERT INTO INTERVENCIONES (ID_USUARIO, ID_TIPO, ID_EQUIPO, MOTIVO, FECHA_HORA, COMENTARIOS)
VALUES ((SELECT ID_USUARIO FROM USUARIOS WHERE NOMBRE_USUARIO LIKE 'admin'), (SELECT ID_TIPO FROM TIPOS_INTERVENCIONES WHERE NOMBRE_TIPO LIKE 'Correctivo'), (SELECT ID_EQUIPO FROM EQUIPOS WHERE NOMBRE LIKE 'Tensiometro'), 'No encendia', TIMESTAMP '2023-11-27 18:30:00', 'Faltaban pilas');
INSERT INTO INTERVENCIONES (ID_USUARIO, ID_TIPO, ID_EQUIPO, MOTIVO, FECHA_HORA, COMENTARIOS)
VALUES ((SELECT ID_USUARIO FROM USUARIOS WHERE NOMBRE_USUARIO LIKE 'admin'), (SELECT ID_TIPO FROM TIPOS_INTERVENCIONES WHERE NOMBRE_TIPO LIKE 'Preventivo'), (SELECT ID_EQUIPO FROM EQUIPOS WHERE NOMBRE LIKE 'Anestesiometro emergencia'), 'Limpiar conductos', TIMESTAMP '2023-11-30 17:00:00', 'Se debe limpiar los conductos por donde viaja la medicacion al paciente.');
-- Se crean los permisos de los perfiles
INSERT INTO PERFILES_PERMISOS (ID_PERFIL, ID_PERMISO) VALUES ((SELECT ID_PERFIL FROM PERFILES WHERE NOMBRE_PERFIL LIKE 'Administrador'), (SELECT ID_PERMISO FROM PERMISOS WHERE TIPO_PERMISO LIKE 'Ver'));
INSERT INTO PERFILES_PERMISOS (ID_PERFIL, ID_PERMISO) VALUES ((SELECT ID_PERFIL FROM PERFILES WHERE NOMBRE_PERFIL LIKE 'Administrador'), (SELECT ID_PERMISO FROM PERMISOS WHERE TIPO_PERMISO LIKE 'Agregar'));
