@startuml
'https://plantuml.com/sequence-diagram
left to right direction
actor Usuario as U
actor Administrador as A

package "Módulo 1 - Gestión de Usuarios" {
  usecase "Registro de Usuario" as CU1
  usecase "Login de Usuario" as CU2
  usecase "Modificación de datos propios del Usuario" as CU3

  U --> CU1
  U --> CU2
  U --> CU3
  A --> CU1
  A --> CU2
}

package "Módulo 2 - Gestión de Perfiles" {
  usecase "Ingreso de Perfiles" as CU4
  usecase "Listado de Perfiles" as CU5
  usecase "Modificación de Perfiles" as CU6
  usecase "Baja de Perfiles" as CU7

  A --> CU4
  A --> CU5
  A --> CU6
  A --> CU7
}

package "Módulo 5 - Gestión de Intervenciones" {
  usecase "Registro de Intervención" as CU8
  usecase "Trabajar Intervención" as CU9
  usecase "Reporte de Intervención por Fechas" as CU10
  usecase "Reporte por tipo de Intervención" as CU11

  U --> CU8
  U --> CU9
  U --> CU10
  U --> CU11
  A --> CU8
  A --> CU9
  A --> CU10
  A --> CU11
}

U --> "Módulo 1 - Gestión de Usuarios" : Utiliza
A --> "Módulo 1 - Gestión de Usuarios" : Utiliza
A --> "Módulo 2 - Gestión de Perfiles" : Utiliza
U --> "Módulo 5 - Gestión de Intervenciones" : Utiliza

@enduml

@startuml
left to right direction
actor Usuario as U
actor Administrador as A

package "Módulo 6 - Gestión de Equipos" {
  usecase "Ingreso de Equipo" as CU12
  usecase "Baja de Equipo" as CU13
  usecase "Modificación de Equipo" as CU14
  usecase "Reporte de Equipo" as CU15

  U --> CU12
  A --> CU12
  A --> CU13
  A --> CU14
  U --> CU14
  A --> CU15
}

U --> "Módulo 6 - Gestión de Equipos" : Utiliza
A --> "Módulo 6 - Gestión de Equipos" : Utiliza

@enduml
@startuml
left to right direction

actor Usuario as U
actor Administrador as A

package "Módulo 7 - Gestión de Ubicaciones" {
  usecase "Ingreso de Ubicaciones" as CU16
  usecase "Modificación de Ubicaciones" as CU17
  usecase "Baja de Ubicaciones" as CU18
  usecase "Movimiento de Equipo" as CU19
  usecase "Listado de Movimiento de Equipo" as CU20

  U --> CU16
  U --> CU17
  U --> CU18
  U --> CU19
  U --> CU20
  A --> CU16
  A --> CU17
  A --> CU18
  A --> CU19
  A --> CU20
}

U --> "Módulo 7 - Gestión de Ubicaciones" : Utiliza
A --> "Módulo 7 - Gestión de Ubicaciones" : Utiliza

@enduml

@startuml
left to right direction
actor Usuario as U
actor Administrador as A

package "Módulo 14 - Gestión de Tipo de Intervención" {
  usecase "Ingreso de Tipo de Intervención" as CU21
  usecase "Listado de Tipo de Intervención" as CU22
  usecase "Modificación de Tipo de Intervención" as CU23
  usecase "Baja de Tipo de Intervención" as CU24

  U --> CU21
  A --> CU21
  A --> CU22
  U --> CU22
  A --> CU23
  U --> CU23
  A --> CU24
  U --> CU24
}

U --> "Módulo 14 - Gestión de Tipo de Intervención" : Utiliza
A --> "Módulo 14 - Gestión de Tipo de Intervención" : Utiliza

@enduml

