@startuml
left to right direction
note "Caso de Uso: CU 001-01 - Registro de Usuario" AS N
:Cualquier\n  Usuario: AS User
rectangle N {
(Registro de Usuario) AS CU1
(Ingresar datos\n usuario) AS E1
(Verificar datos) AS E2
(Error de registro) AS E3
}
User --> CU1
CU1 ..>E1 : <<Include>>
E2 <-right. E1 : <<Include>>
E3 .right--|> CU1: <<Extends>>
@enduml

@startuml
left to right direction
note "Caso de Uso: CU 001-02 - Listado de Usuarios" AS N
:      Administrador\nAuxiliar Administrativo: AS User
rectangle N {
(Listado de Usuarios) AS CU2
(Visualizar Usuarios) AS E1
(Filtrar Datos) AS E2
(Error de Listado) AS E3
}
User --> CU2
CU2 ..> E1 : <<Include>>
E2 -left.|> CU2 : <<Extends>>
E3 ..right--|> CU2: <<Extends>>
@enduml

@startuml
left to right direction
note "Caso de Uso: CU 001-03 - Modificar Usuarios" AS N
:      Administrador\nAuxiliar Administrativo: AS User
rectangle N {
(Modificar Usuarios) AS CU4
(Acceder a ficha\n de usuario) AS E1
(Confirmar Cambios) AS E2
(Validar Cambios) AS E3
(Cancelar Cambios) AS E4
(Actualizar Listado\n de Usuarios) AS E5
}
User --> E1
E1 --> CU4 : <<Include>>
CU4 .left.> E2 : <<Include>>
E3 <..right- CU4: <<Include>>
E4 ..|> E2 : <<Extends>>
E3 -left.> E5 : <<Include>>
@enduml

@startuml
left to right direction
note "Caso de Uso: CU 001-04 - Baja de Usuarios" AS N
:       Administrador\nAuxiliar Administrativo: AS User
rectangle N {
(Baja de Usuarios) AS CU4
(Acceder a ficha\n de usuario) AS E1
(Confirmar Baja) AS E2
(Validar Baja) AS E3
(Cancelar Baja) AS E4
(Actualizar Listado\n de Usuarios) AS E5
(Reactivar Usuario) AS E6
}
User --> E1
E1 --> CU4
CU4 .left.> E2 : <<Include>>
E3 <..right- CU4: <<Include>>
E4 ..|> E2 : <<Extends>>
E3 -left.> E5 : <<Include>>
E6 ..|> CU4 : <<Extends>>
@enduml

@startuml
left to right direction
note "Caso de Uso: CU 001-05 - Login de Usuarios" AS N
:Usuario Registrado: AS User
rectangle N {
(Login de Usuarios) AS CU5
(Acceso al Sistema) AS E1
(Error de Acceso) AS E2
(Verificar Datos de Ingreso) AS E3
}
User --> CU5
E1 <.. E3 : <<Include>>
E2 .right-|> E3 : <<Extends>>
CU5 .-> E3: <<Include>>
@enduml

@startuml
left to right direction
note "Caso de Uso: CU 001-06 - Modificación de datos propios del Usuario" AS N
:Usuario Registrado: AS User
rectangle N {
(Modificar datos\n personales) AS CU4
(Acceder a ficha\n personal) AS E1
(Confirmar Cambios) AS E2
(Validar Cambios) AS E3
(Cancelar Cambios) AS E4
(Actualización de datos\n personales) AS E5
}
User --> E1
E1 --> CU4 : <<Include>>
CU4 .left.> E2 : <<Include>>
E3 <..right- CU4: <<Include>>
E4 ..|> E2 : <<Extends>>
E3 -left.> E5 : <<Include>>
@enduml

@startuml
left to right direction
note "Caso de Uso: CU 002-01 - Ingreso de Perfil" AS N
:       Administrador\nAuxiliar Administrativo: AS User
rectangle N {
(Ingreso de Perfil) AS CU7
(Ingresar datos\n de Perfil) AS E1
(Verificar datos) AS E2
(Error de registro) AS E3
(Registro Exitoso) AS E4
}
User --> CU7
CU7 ..>E1 : <<Include>>
E2 <-right. E1: <<Include>>
E3 ..right--|> CU7: <<Extends>>
E2 .> E4 : <<Include>>
@enduml

@startuml
left to right direction
note "Caso de Uso: CU 002-02 - Listado de Perfiles" AS N
:      Administrador\nAuxiliar Administrativo: AS User
rectangle N {
(Listado de Perfiles) AS CU8
(Visualizar Perfil) AS E1
(Filtrar Datos) AS E2
(Error de Listado) AS E3
}
User --> CU8
CU8 ..> E1 : <<Include>>
E2 -left.|> CU8 : <<Extends>>
E3 ..right--|> CU8: <<Extends>>
@enduml

@startuml
left to right direction
note "Caso de Uso: CU 002-03 - Modificar Perfiles" AS N
:      Administrador\nAuxiliar Administrativo: AS User
rectangle N {
(Modificar Perfiles) AS CU9
(Acceder a ficha\n del Perfil) AS E1
(Confirmar Cambios) AS E2
(Validar Cambios) AS E3
(Cancelar Cambios) AS E4
(Actualizar Listado\n de Perfiles) AS E5
}
User --> E1
E1 --> CU9 : <<Include>>
CU9 .left.> E2 : <<Include>>
E3 <..right- CU9: <<Include>>
E4 ..|> E2 : <<Extends>>
E3 -left.> E5 : <<Include>>
@enduml

@startuml
left to right direction
note "Caso de Uso: CU 002-04 - Baja de Perfil" AS N
:       Administrador\nAuxiliar Administrativo: AS User
rectangle N {
(Baja de Perfil) AS CU10
(Acceder al listado\n de Perfiles) AS E1
(Confirmar Baja) AS E2
(Validar Baja) AS E3
(Cancelar Baja) AS E4
(Actualizar Listado\n de Perfiles) AS E5
(Reactivar Perfil) AS E6
}
User --> E1
E1 --> CU10 : <<Include>>
CU10 .left.> E2 : <<Include>>
E3 <..right- CU10: <<Include>>
E4 ..|> E2 : <<Extends>>
E3 -left.> E5 : <<Include>>
E6 ..|> CU10 : <<Extends>>
@enduml

@startuml
left to right direction
note "      Administrador\nAuxiliar Administrativo\n Ingeniero Biomédico\n         Técnologo\n           Técnico" as N2
note "Caso de Uso: CU 005-01 - Registro de Intervención" AS N
:Usuario Registrado: AS User
rectangle N {
(Registro de Intervención) AS CU11
(Ingresar datos\n de Intervención) AS E1
(Confirmar Registro) AS E2
(Error de registro) AS E3
(Registro Exitoso) AS E4
}
User --> CU11
CU11 ..>E1 : <<Include>>
E2 <-right. E1: <<Include>>
E3 ..right--|> CU11: <<Extends>>
E2 .> E4 : <<Include>>
N2 .left-> User
@enduml

@startuml
left to right direction
note "      Administrador\nAuxiliar Administrativo\n Ingeniero Biomédico\n         Técnologo\n           Técnico" as N2
note "Caso de Uso: CU 005-02 - Trabajar Intervenciones" AS N
:Usuario Registrado: AS User
rectangle N {
(Trabajar Intervención) AS CU12
(Acceder al Historial\n de Intervenciones) AS E1
(Actualizar datos de\n la intervención) AS E2
(Validar Cambios) AS E3
(Actualizar Registro) AS E5
}
User --> E1
E1 -left-> CU12 : <<Include>>
CU12 ..> E2 : <<Include>>
E3 <..right- E2: <<Include>>
E3 -left.> E5 : <<Include>>
N2 .left-> User
@enduml

@startuml
left to right direction
note "      Administrador\nAuxiliar Administrativo\n Ingeniero Biomédico\n         Técnologo\n           Técnico" as N2
note "Caso de Uso: CU 005-03 - Reporte de Intervención por Fechas" AS N
:Usuario Registrado: AS User
rectangle N {
(Reporte de Intervención\n por Fechas) AS CU13
(Acceder al Historial\n de Intervenciones) AS E1
(Filtrar registros por\n fecha de la intervención) AS E2
(Visualizar Reporte\n de la intervención) AS E3
(Reporte sin datos) AS E4
}
User --> E1
E1 -left-> CU13 : <<Include>>
CU13 ..> E2 : <<Include>>
E3 <..right- E2: <<Include>>
E4 ..|> E2: <<Extends>>
N2 .left-> User
@enduml

@startuml
left to right direction
note "      Administrador\nAuxiliar Administrativo\n Ingeniero Biomédico\n         Técnologo\n           Técnico" as N2
note "Caso de Uso: CU 005-04 - Reporte por Tipo de Intervención" AS N
:Usuario Registrado: AS User
rectangle N {
(Reporte por Tipo de Intervención) AS CU14
(Acceder al Historial\n de Intervenciones) AS E1
(Filtrar registros) AS E2
(Visualizar Reporte\n de la intervención) AS E3
(Reporte sin datos) AS E4
}
User --> E1
E1 -left-> CU14 : <<Include>>
CU14 <|.. E2 : <<Extends>>
CU14 ..> E3: <<Include>>
E4 ..|> E2: <<Extends>>
N2 .left-> User
@enduml

@startuml
left to right direction
note "      Administrador\nAuxiliar Administrativo\n Ingeniero Biomédico\n         Técnologo\n           Técnico" as N2
note "Caso de Uso: CU 006-01 - Ingreso de Equipos" AS N
:Usuario Registrado: AS User
rectangle N {
(Ingreso de Equipos) AS CU15
(Completar datos\n de Equipo) AS E1
(Confirmar Registro) AS E2
(Error de registro) AS E3
(Registro Exitoso) AS E4
(Cancelar Ingreso) AS E5
}
User --> CU15
CU15 ..>E1 : <<Include>>
E2 <-right. E1: <<Include>>
E3 ..right--|> CU15: <<Extends>>
E2 .> E4 : <<Include>>
N2 .left-> User
E5 ..|> E2 : <<Extends>>
@enduml

@startuml
left to right direction
note "      Administrador\nAuxiliar Administrativo\n Ingeniero Biomédico\n         Técnologo\n           Técnico" as N2
note "Caso de Uso: CU 006-02 - Baja de Equipo" AS N
:Usuario Registrado: AS User
rectangle N {
(Baja de Equipo) AS CU16
(Completar los campos\n requeridos) AS E1
(Confirmar Baja de Equipo) AS E2
(Error Datos Inválidos) AS E3
(Actualización de Equipos registrados) AS E4
(Cancela Baja) AS E5
}
User --> CU16
CU16 ..>E1 : <<Include>>
E2 <-right. E1: <<Include>>
E3 ..right--|> CU16: <<Extends>>
E2 .> E4 : <<Include>>
E5 ..|> E2 : <<Extends>>
N2 .left-> User
@enduml

@startuml
left to right direction
note "      Administrador\nAuxiliar Administrativo\n Ingeniero Biomédico\n         Técnologo\n           Técnico" as N2
note "Caso de Uso: CU 006-03 - Modificación de Equipo" AS N
:Usuario Registrado: AS User
rectangle N {
(Modificación de Equipos) AS CU17
(Completar los campos\n requeridos) AS E1
(Confirmar Actualización de Equipo) AS E2
(Error Datos Inválidos) AS E3
(Actualización de Equipos registrados) AS E4
(Cancelar Modificación) AS E5
(Acceder al listado \nde Equipos Registrados) AS E6
}
User --> E6
E6 --> CU17 :<<Include>>
CU17 ..>E1 : <<Include>>
E2 <-. E1: <<Include>>
E3 .-|> CU17: <<Extends>>
E2 .> E4 : <<Include>>
E5 .-|> E2 : <<Extends>>
N2 .left-> User
@enduml

@startuml
left to right direction
note "      Administrador\nAuxiliar Administrativo\n Ingeniero Biomédico\n         Técnologo\n           Técnico" as N2
note "Caso de Uso: CU 006-04 - Reporte de Equipos" AS N
:Usuario Registrado: AS User
rectangle N {
(Reporte de Equipos) AS CU18
(Visualizar reportes \nde Equipos) AS E1
(Filtrar la busqueda) AS E2
(Error Filtro Inválidos) AS E3
(Acceder al listado \nde Equipos Registrados) AS E6
}
User --> E6
E6 --> CU18 :<<Include>>
CU18 ..>E1 : <<Include>>
E2 .-|> E1: <<Extends>>
E3 .-|> CU18: <<Extends>>
N2 .ri-> User
@enduml

@startuml
left to right direction
note "      Administrador\nAuxiliar Administrativo\n Ingeniero Biomédico\n         Técnologo\n           Técnico" as N2
note "Caso de Uso: CU 007-01 - Ingreso de Ubicación" AS N
:Usuario Registrado: AS User
rectangle N {
(Ingreso de Ubicación) AS CU19
(Completar datos\n de la Ubicación) AS E1
(Confirmar Registro) AS E2
(Error de registro) AS E3
(Registro Exitoso) AS E4
(Cancelar Ingreso) AS E5
}
User --> CU19
CU19 ..>E1 : <<Include>>
E2 <. E1: <<Include>>
E3 ..right--|> CU19: <<Extends>>
E2 .> E4 : <<Include>>
N2 .left-> User
E5 ..|> E2 : <<Extends>>
@enduml

@startuml
left to right direction
note "      Administrador\nAuxiliar Administrativo\n Ingeniero Biomédico\n         Técnologo\n           Técnico" as N2
note "Caso de Uso: CU 007-02 - Modificación de Ubicaciones" AS N
:Usuario Registrado: AS User
rectangle N {
(Modificación de Ubicaciones) AS CU20
(Completar los campos\n a modificar) AS E1
(Confirmar Actualización\n de la Ubicación) AS E2
(Error Datos Inválidos) AS E3
(Actualización de Ubicaciones\n en la Institución) AS E4
(Cancelar Modificación) AS E5
}
User ---> CU20
CU20 ..>E1 : <<Include>>
E2 <-. E1: <<Include>>
E3 .-|> CU20: <<Extends>>
E2 .> E4 : <<Include>>
E5 .-|> E2 : <<Extends>>
N2 .left-> User
@enduml

@startuml
left to right direction
note "      Administrador\nAuxiliar Administrativo\n Ingeniero Biomédico\n         Técnologo\n           Técnico" as N2
note "Caso de Uso: CU 007-03 - Baja de Ubicación" AS N
:Usuario Registrado: AS User
rectangle N {
(Baja de Ubicación) AS CU21
(Completar los campos\n requeridos) AS E1
(Confirmar Eliminación\n de la Ubicación) AS E2
(Ubicación Eliminada) AS E4
(Cancelar Baja) AS E5
(Listado de Ubicaciones) AS E6
}
User --> E6
E6 -> CU21
CU21 ..>E1 : <<Include>>
E2 <. E1: <<Include>>
E2 .> E4 : <<Include>>
E5 .-|> E2 : <<Extends>>
N2 .right-> User
@enduml

@startuml
left to right direction
note "      Administrador\nAuxiliar Administrativo\n Ingeniero Biomédico\n         Técnologo\n           Técnico" as N2
note "Caso de Uso: CU 007-04 - Movimiento de Equipo" AS N
:Usuario Registrado: AS User
rectangle N {
(Movimiento de Equipo) AS CU22
(Ingresar Datos) AS E1
(Confirmar Movimiento del Equipo) AS E2
(Actualización de datos) AS E4
(Cancelar Modificación) AS E5
}
User --> CU22
CU22 ..>E1 : <<Include>>
E2 <. E1: <<Include>>
E2 .> E4 : <<Include>>
E5 .-|> E2 : <<Extends>>
N2 .left-> User
@enduml

@startuml
left to right direction
note "      Administrador\nAuxiliar Administrativo\n Ingeniero Biomédico\n         Técnologo\n           Técnico" as N2
note "Caso de Uso: CU 007-05 - Listado de Movimiento de Equipos" AS N
:Usuario Registrado: AS User
rectangle N {
(Listado de Movimiento\n de Equipos) AS CU23
(Filtrar Registros) AS E1
(Visualizar reporte) AS E4
}
User --> CU23
CU23 <|.. E1 : <<Extends>>
CU23 ..>E4 : <<Include>>
E1 ..> E4
N2 .left-> User
@enduml

@startuml
left to right direction
note "Caso de Uso: CU 014-01 - Ingreso de Tipo de Intervención" AS N
:Auxiliar Administrativo: AS User
rectangle N {
(Ingreso de Tipo\n de Intervención) AS CU24
(Ingresar datos) AS E1
(Confirmar Tipo de Intervención) AS E2
(Error de registro) AS E3
(Registro Exitoso) AS E4
(Cancelar Ingreso) AS E5
}
User --> CU24
CU24 ..>E1 : <<Include>>
E2 <. E1: <<Include>>
E3 ..right--|> CU24: <<Extends>>
E2 .> E4 : <<Include>>
E5 ..|> E2 : <<Extends>>
@enduml

@startuml
left to right direction
note "Caso de Uso: CU 014-02 - Listado de Tipo de Intervención" AS N
:Auxiliar Administrativo: AS User
rectangle N {
(Listado de Tipo\n de Intervención) AS CU25
(Filtrar Listado) AS E1
(Visualizar Tipos de\n Intervenciones Registrados) AS E2
}
User --> CU25
CU25 <|..E1 : <<Extends>>
CU25 ..> E2: <<Include>>
E2 <. E1: <<Include>>
@enduml

@startuml
left to right direction
note "Caso de Uso: CU 014-03 - Modificar Tipo de Intervención" AS N
:Auxiliar Administrativo: AS User
rectangle N {
(Modificar Tipo\n de Intervención) AS CU26
(Completar los campos\n a modificar) AS E1
(Confirmar Actualización\n de datos) AS E2
(Actualización Exitosa) AS E4
(Cancelar Modificación) AS E5
(Listado de Tipos \nde Intervenciones) AS E6
}
User ---> E6
E6 --> CU26
CU26 .down->E1 : <<Include>>
E2 <-. E1: <<Include>>
E2 .> E4 : <<Include>>
E5 .-|> E2 : <<Extends>>
@enduml

@startuml
left to right direction
note "Caso de Uso: CU 014-04 - Baja de Tipo de Intervención" AS N
:Auxiliar Administrativo: AS User
rectangle N {
(Baja de Tipo\n de Intervención) AS CU27
(Confirmar Actualización\n de datos) AS E2
(Baja Exitosa) AS E4
(Cancelar Baja) AS E5
}
User ---> CU27
CU27 .down->E2 : <<Include>>
E2 .> E4 : <<Include>>
E5 .-|> E2 : <<Extends>>
@enduml