@startuml
left to right direction
actor Usuario as Usuario
actor Auxiliar_Administrativo as "Auxiliar Administrativo / Administrador"
actor Ingeniero as "Ingeniero biomedico"
actor Técnico as Técnico


package "Gestión de usuarios" {

usecase "Registro de usuario" as UC1
usecase "Ver Listado de usuarios" as UC2
usecase "Modificar datos de usuario" as UC3
usecase "Eliminar usuario" as UC4
usecase "Crear perfiles" as UC6

Usuario ----> UC1



Auxiliar_Administrativo --> UC2

Auxiliar_Administrativo --> UC3


Auxiliar_Administrativo --> UC4


Auxiliar_Administrativo ----> UC6

Ingeniero ----> UC6
Técnico ---> UC6
}
@enduml

@startuml
left to right direction
actor Auxiliar_Administrativo as "Admin / Auxiliar Administrativo"
'actor Administrador as Administrador

package "Gestión de perfiles" {
usecase "Crear perfiles" as UC7
usecase "Listar perfiles" as UC8
usecase "Modificar perfiles" as UC9
usecase "Eliminar perfiles" as UC10

'Administrador --> UC7
Auxiliar_Administrativo ---> UC7

'Administrador --> UC8
Auxiliar_Administrativo --> UC8

'Administrador --> UC9
Auxiliar_Administrativo --> UC9

'Administrador --> UC10
Auxiliar_Administrativo --> UC10
}
@enduml


@startuml
left to right direction
actor Grupo as "Admin / Aux Admin/Ingeniero biomedico /Técnico"

package "Gestión de intervenciones" {
usecase "Registro de intervencion" as UC11
usecase "Trabajar intervencion" as UC12
usecase "Reporte de Intervención por fechas" as UC13
usecase "Reporte por tipo de intervencion" as UC14
}

package "Gestión de equipos" {
usecase "Ingreso de equipo" as UC15
usecase "Baja de equipo" as UC16
usecase "Modificación de equipo" as UC17
usecase "Reporte de equipos" as UC18
}

UC11 <-- Grupo
UC12 <-- Grupo
UC13 <-- Grupo
UC14 <-- Grupo

Grupo --> UC15

Grupo --> UC16

Grupo --> UC17

Grupo --> UC18
@enduml
